name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Delete release
      id: delete_release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Rename file 
      run: mv target/ps4-remote-pkg-installer.jar target/ps4-remote-pkg-installer.${{ github.ref_name }}.jar
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: target/ps4-remote-pkg-installer.${{ github.ref_name }}.jar
        replacesArtifacts: true
